# Generated by Django 3.2.8 on 2021-10-22 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='item',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='item',
            field=models.ManyToManyField(to='hub.menu_item'),
        ),
        migrations.AlterField(
            model_name='qr_link_resolve',
            name='qr_code_id',
            field=models.CharField(default='XJSql6znWJna1mbNzbi9OdzlhsA6M3GJijZxBwhLD9UlsLTgUX', max_length=50),
        ),
    ]
