# Generated by Django 3.2.8 on 2021-10-22 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0002_auto_20211022_1730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='item',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='item',
            field=models.ForeignKey(default=121221, on_delete=django.db.models.deletion.CASCADE, to='hub.menu_item'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='qr_link_resolve',
            name='qr_code_id',
            field=models.CharField(default='GAdJJmFaznzv7aXFQIOLaRfCEv3bnE8y0ZMaRsjMfkDs0YjOc3', max_length=50),
        ),
    ]
