# Generated by Django 3.2.8 on 2021-10-22 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0003_auto_20211022_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qr_link_resolve',
            name='qr_code_id',
            field=models.CharField(default='eKKrHiBBNxpJcYcAx8hxbggrs9qIOXndsbYgd24j8UyxmHUqrr', max_length=50),
        ),
    ]
