# Generated by Django 3.2.8 on 2021-10-22 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0004_alter_qr_link_resolve_qr_code_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qr_link_resolve',
            name='qr_code_id',
            field=models.CharField(default='ZJnDCFwK56omeujzno5Nxt9EpwdWAsmxIlI5YqR7CAWEKhP1ZE', max_length=50),
        ),
    ]
