# Generated by Django 3.2.8 on 2021-10-23 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0005_alter_qr_link_resolve_qr_code_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='user',
            new_name='sender',
        ),
        migrations.AddField(
            model_name='room',
            name='branch_id',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='room',
            name='message_receivers',
            field=models.ManyToManyField(to='hub.user_info'),
        ),
        migrations.AddField(
            model_name='room',
            name='restaurant_id',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='qr_link_resolve',
            name='qr_code_id',
            field=models.CharField(default='AbgAn3hg4sk1W77Jt0VFfoaOueGx83tgP0LFOig7KpxXFYV0TS', max_length=50),
        ),
    ]
