# Generated by Django 3.2.8 on 2021-10-23 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0006_auto_20211023_1647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='message_receivers',
        ),
        migrations.AddField(
            model_name='room',
            name='room_clearance',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='qr_link_resolve',
            name='qr_code_id',
            field=models.CharField(default='MFMpNAb0alQ8ZyKOLbTb5bK7vYRuQItaNmBUIyjY5cZzeJOyj4', max_length=50),
        ),
    ]
