# Generated by Django 3.2.8 on 2021-10-23 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0008_alter_qr_link_resolve_qr_code_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='branch_id',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='message',
            name='restaurant_id',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='message',
            name='table_id',
            field=models.IntegerField(default=-1),
        ),
    ]
