# Generated by Django 3.2.8 on 2021-10-24 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0009_auto_20211023_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
