# Generated by Django 3.2.8 on 2021-10-25 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0010_message_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qr_link_resolve',
            name='qr_code_id',
            field=models.CharField(default='nOyRobo25qgYVc2ZzX4O9WFyNCw2y6yjQcFelNvoibTymxwavs', max_length=50),
        ),
    ]
