# Generated by Django 3.2.8 on 2021-10-25 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0012_auto_20211025_2343'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='branch_id',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='order',
            name='restaurant_id',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='order',
            name='table_id',
            field=models.IntegerField(default=-1),
        ),
    ]
