# Generated by Django 3.2.8 on 2021-10-28 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0013_auto_20211026_0056'),
    ]

    operations = [
        migrations.CreateModel(
            name='branch_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_id', models.IntegerField(default=-1)),
                ('branch_id', models.IntegerField(default=-1)),
                ('longtitute', models.CharField(max_length=100)),
                ('latitude', models.CharField(max_length=100)),
            ],
        ),
    ]
