# Generated by Django 3.2.8 on 2021-11-04 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0017_auto_20211029_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch_info',
            name='branch_id',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='branch_info',
            name='restaurant_id',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='menu_item',
            name='branch_id',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='menu_item',
            name='restaurant_id',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='message',
            name='branch_id',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='message',
            name='restaurant_id',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='order',
            name='branch_id',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='order',
            name='restaurant_id',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='qr_link_resolve',
            name='branch_id',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='qr_link_resolve',
            name='restaurant_id',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='room',
            name='branch_id',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='room',
            name='restaurant_id',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='branch_name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='restaurant_id',
            field=models.CharField(max_length=500),
        ),
    ]
