# Generated by Django 3.2.8 on 2021-11-04 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0018_auto_20211104_1348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_info',
            name='branch_name',
        ),
        migrations.RemoveField(
            model_name='user_info',
            name='restaurant_name',
        ),
    ]
