# Generated by Django 3.2.8 on 2021-11-04 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0019_auto_20211104_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='branch_id',
            field=models.CharField(max_length=500),
        ),
    ]
