# Generated by Django 3.2.8 on 2021-11-14 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0020_alter_user_info_branch_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=1000000)),
                ('stars', models.IntegerField()),
            ],
        ),
    ]
